### ISSUE TITLE
Property values are mismatched

### ISSUE THREAD

**Issue by vaibhavrmore1** [xan105/node-win-tasklist#4]
When I use the below code snippet, the result returned has a mismatch in property and their values returned.

    const tasklist = require('win-tasklist');

    tasklist.getProcessInfo("explorer.exe",{verbose: true}).then((process)=>{
    console.log(process);
  
     }).catch((err)=>{
      console.error(err);
    });
    
    
  The result returned for me is:

    [ {
    process: 'explorer.exe',
    pid: 8384,
    sessionType: 'console',
    sessionNumber: 1,
    memUsage: 1024,
    state: '63',
    user: '228 K',
    cpuTime: 'Running',
    windowTitle: 'XXXXX\\vaibhav.more'
    }]

This is happening for the properties after memUsage i.e. more likely when verbose is true.

This is happening for any process query. 
Is there any workaround or solution for it as the properties I am interested in are processName, pid, and userName.

**Comment by xan105** [comment]
May I ask under which OS and language did you get these results ?

**Comment by xan105** [comment]
Can you try with the above change ? I can't seem to reproduce the conditions of your issue.

**Comment by vaibhavrmore1** [comment]
> May I ask under which OS and language did you get these results ?

OS is Windows and Language used is Node js (Console app)

**Comment by vaibhavrmore1** [comment]
You are right, looks like it was caused by a comma in the memUsage value.

It works fine with your new change.

But the memUsage value seems to be converted into a different format.

The result from code :

    [{
    process: 'explorer.exe',
    pid: 8384,
    sessionType: 'console',
    sessionNumber: 1,
    memUsage: 173838336,
    state: 'running',
    user: 'XXXXX\\vaibhav.more',
    cpuTime: '1:12:41',
    windowTitle: 'N/A'
    }]
    
    
The result from command prompt:
    
 Image Name                     PID Session Name        Session#    Mem Usage Status          User Name                                              CPU Time Window Title
========================= ======== ================ =========== ============ =============== ================================================== ============ ========================================================================
explorer.exe                  8384 Console                    1   1,70,164 K Running         XXXX\vaibhav.more                                1:12:41 N/A

**Comment by xan105** [comment]
memUsage is converted into bytes ( * 1024)

**Comment by vaibhavrmore1** [comment]
Ok. You can make a release for the fix and let me know.

Thanks
