### ISSUE TITLE
Is it possible to get command line arguments for the fetched process?

### ISSUE THREAD

**Issue by vaibhavrmore1** [xan105/node-win-tasklist#5]
Is the property available to get command-line arguments for the fetched process?

Or please can you add a new property that will give us the command line arguments used to launch the process initially?

**Comment by xan105** [comment]
Idk this feels out of scope of the project: `tasklist` doesn't provide this info on its own.
You can use `wmic` however : 

```js
"use strict";

const { exec } = require("child_process");
const { promisify } = require("util");

async function getCmdLine(pid){
  
  const cmd = await promisify(exec)(`wmic process where processid='${pid}' get commandline /value`);
  if (cmd.stderr) throw new Error(cmd.stderr);
  const cmdLine = cmd.stdout.trim().replace(/^CommandLine=".+"/,"").trim();
  return cmdLine;

}

(async()=>{

const cmdLine = await getCmdLine(9816);
console.log(cmdLine);

})().catch(console.error);
```

**Comment by vaibhavrmore1** [comment]
Right. It can be accessed via wmic.
I will use the function to get command lines whenever required.

Does this command execution require admin permissions for the running process?

**Comment by xan105** [comment]
Command can be use in user-land without privileges but I don't know if you can query an elevated process for its information while you aren't elevated yourself (_probably not_)

**Comment by vaibhavrmore1** [comment]
Expected behaviour should be like, if the process is listed using "tasklist -v" for a user then the user should be able to query the more info about that process.

**Comment by vaibhavrmore1** [comment]
Newly added code should be good enough to get the required information.
Just observation that by default command line is inclusive of exe path. (Seen via C# code).

**Comment by xan105** [comment]
> Just observation that by default command line is inclusive of exe path. (Seen via C# code).

Yeah I've noticed that arg0 _usually_ has it but anyhow it was easier to deal with it this way.

**Comment by vaibhavrmore1** [comment]
Are you gonna release the new changes soon?

**Comment by xan105** [comment]
Sorry there are still additions and testing I'd like to do. Meanwhile you can 
`npm i xan105/win-tasklist` or `npm i https://github.com/xan105/node-win-tasklist` if that's urgent

**Comment by vaibhavrmore1** [comment]
I see that you are converting the modules from **CJS to ES6**. I used this package in my backend/desktop app as it was written in cjs because ES6 modules are not supported easily by **PKG** to convert them into exe.

Still, I tried again and encountered the same error.

Command used is :  `pkg -t node10-win-x64 --compress GZip -o ".\Upgrader.exe" "."
`

Error thrown is,

    > pkg@5.3.1
    compression:  GZip
    > Warning Entry 'main' not found in %1
    %1: C:\Users\Vaibhav Raghunath\Desktop\ES6WinTaskLit\node_modules\win-tasklist\package.json
    %2: C:\Users\Vaibhav Raghunath\Desktop\ES6WinTaskLit\app.js
    > Warning Failed to make bytecode node10-x64 for file C:\snapshot\ES6WinTaskLit\app.js

You can help out if you have any idea about it.

Code snippet used is,

    import { getProcessInfo } from 'win-tasklist';

    getProcessInfo("Teams.exe", { verbose: true }).then((process) => {
        console.log(process);
    }).catch((err) => {
        console.error(err);
          });`


Package.json,
```
{
  "name": "sample",
  "version": "1.0.0",
  "description": "Auto Upgrader File",
  "main": "app.js",
  "bin": "app.js",
  "type": "module",
  "dependencies": {
    "win-tasklist": "git+https://github.com/xan105/node-win-tasklist.git"
  }
}

```

**Comment by xan105** [comment]
Ah sorry for the change. I'm slowly converting all my packages to ESM only instead of the previously CJS+ESM wrapper.
Since I was adding stuff to this package I took the opportunity to convert it to pure ESM.

I don't think you can use ESM in CJS 🤔. I know you can use CJS in ESM tho.

The error throwed by pkg refers to this:
add `"main": "./lib/esm.js",` to the `package.json` file of `.\node_modules\win-tasklist`
This entry is no longer used and `exports:` is preferred.

Sorry for the inconvenience really.

**Comment by vaibhavrmore1** [comment]
Yes, ESM can't be used in CJS but it works the other way round. Hence I tried changing all my code to ESM and it works when called directly via filename but the packaging wasn't successful. PKG is the only reliable source that converts nodejs to the exe and it throws the above error for  ESM code.

I have tried using `export` as well for the functions but it's PKG which doesn't work here and no solution was found for it.

In that case, I might have to use your 1.1.1 version and add the logic on my own whichever is required. Eg. GetCommandLines

**Comment by xan105** [comment]
I suppose PKG will be updated later on to properly support ESM. Again, sorry for the trouble. Feel free to use the code in `lib/wmic.js` as you'd like since the module is under a MIT license anyway.

I'm closing this. The original topic has been covered and implemented.
